version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: pg-epicalendar
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "epicalendar"
    env_file:
      - .env
    networks:
      - api_db
    restart: unless-stopped
  api:
    container_name: api-epicalendar
    depends_on:
      - postgres
    build: ./api
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    networks:
      - api_db
volumes:
  postgres_data:
networks:
  api_db: