spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/epicalendar
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}