CREATE TABLE IF NOT EXISTS activities (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    event_id int NOT NULL,
    mail varchar(128) NOT NULL,
    title varchar(256) NOT NULL,
    room varchar(128),
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS modules (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    code varchar(9) NOT NULL,
    year int NOT NULL
);
CREATE TABLE IF NOT EXISTS module_subscriptions (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    module_id int NOT NULL,
    mail varchar(128) NOT NULL,
    FOREIGN KEY (module_id) REFERENCES modules(id)
);
CREATE TABLE IF NOT EXISTS projects (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar(256) NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    module_id int NOT NULL,
    FOREIGN KEY (module_id) REFERENCES modules(id)
);